### ISSUE TITLE
total time require for training

### ISSUE THREAD

**Issue by AFNANAMIN** [naver/biobert-pretrained#10]
i am running "run_ner" file  for training about 7 to 8 hours in colab and model won't show any progress
![image](https://user-images.githubusercontent.com/33934146/66278932-2d709680-e8c7-11e9-8829-1a41c4deedff.png)
output of the training is like above is there any error?

**Comment by jhyuklee** [comment]
Hi,

it seems that the code is running on cpus not on gpus. Otherwise, check hyperparameters like batch size.

(it would be nice to post finetuning related issues in dmis-lab/biobert)

Thanks!

**Comment by AFNANAMIN** [comment]
can you plz tell  the estimated amount of time required in training i am using the same data provided in your  github repo

**Comment by wonjininfo** [comment]
Hi @afnanamin, it depends on the task and the dataset.
For NER, training would usually takes 1~20 hours (with gpu; titan xp) depends on the settings and the dataset. It may take longer if you wish to get the best score. 
Thanks!
Wonjin
