### ISSUE TITLE
Regarding Relation Extraction (RE), does it mean it's classifying whether the two marked entities have the defined relations?

### ISSUE THREAD

**Issue by v-loves-avocados** [naver/biobert-pretrained#12]
First of all, thank you for biobert!

I am very new to biobert. 

When I first heard about the name 'relation extraction', I thought it would be something like this:

Input:  Gene123 may be a predictor of disease123, but not disease456.
Output from biobert:  gene123, disease123

-------------------
Question 1: Is my understanding below right?

As I learned more about biobert, it seems to me that the idea is:

Input: ___ may be a predictor of ___, but not disease456.
Output: 1 (yes, the two masked tokens have the defined relation). 

Or:

Input: ___ may be a predictor of disease123, but not ___
Output: 0 (no, the two masked tokens do not have the defined relation).

----------------

Question 2:  If my understanding above is right, if I want to achieve the goal of inputting a sentence, and outputting a pair gene-disease, does it mean I need the following structure?
 
step 1: Entity Extraction of the genes and disease entities.  
Output: gene123, disease123, disease456.

step 2: Try all the possible pairing of the two entities:
gene123-disease123, 
gene123-disease456, 
disease123-disease456

and classify if the pairs form the relation. 

Output:
gene123-disease123: 1
gene123-disease456: 0
disease123-disease456: 0

Thank you for taking the time to answer my questions!

**Comment by jhyuklee** [comment]
Question 1: Is my understanding below right?
=> Yes, and each entity is replaced with its unique token.

Question 2: If my understanding above is right, if I want to achieve the goal of inputting a sentence, and outputting a pair gene-disease, does it mean I need the following structure?
=> Yes, you have to do NER by yourself for classifying the relation.

Thanks.
