### ISSUE TITLE
Pre-trained BioBERT를 distilBERT처럼 사용하려면

### ISSUE THREAD

**Issue by SeungJinWang** [naver/biobert-pretrained#15]
안녕하세요.
먼저, 우수한 눈문과 결과로 대한민국인의 자부심을 느끼게 해주셔서 정말 감사드립니다.
문의 드릴 일이 있어 글을 남깁니다.
Pre-trained BioBERT도 distilBERT 처럼 사용이 가능한건가요?
일반적인 연구환경에서는 대용량의 컴퓨터와 GPU를 구비하기 힘들다는 것은 잘 아시리라 생각됩니다.
그래서 일반 연구원들이 BioBERT의 우수한 성능을 활용할 수 있는 방법은 없을가요?
감사합니다.

**Comment by jhyuklee** [comment]
안녕하세요 @SeungJinWang 님, 현재 BioBERT는 distillation이 된 버전이 존재하지 않습니다. fine-tuning 실험으로 사용되는 GPU는 12GB의 Titan X 정도면 충분합니다. 데이터셋도 작아 시간도 오래 걸리지 않으니 참고바랍니다. 감사합니다!
