### ISSUE TITLE
BIOBERT corpus

### ISSUE THREAD

**Issue by etetteh** [naver/biobert-pretrained#17]
Congratulations on the BIOBERT work. I am trying to train BIOBERT from scratch with slight modifications.
The vocab.txt is the original.
Please, can you provide me with help on getting the PubMed Abstracts, PMC full articles texts and the original BERT corpus? I can't seem to find a way in getting these files.

**Comment by jhyuklee** [comment]
Hi, did you check the README of our repository? There are links to the corpora. Regarding the original BERT corpus, please check from google's repository. Thanks.

**Comment by etetteh** [comment]
Thank you for your reply, but the only links I'm seeing those for the
downstream tasks not the pubmed data itself.

**Comment by jhyuklee** [comment]
Please check [here](https://github.com/naver/biobert-pretrained#pre-training-corpus). Thanks.

**Comment by LivC193** [comment]
Hi, 
This is the function I use to get Abstracts as well as other information:
```
try:
         handle = Entrez.efetch(db = 'pubmed',
                                retmode = 'text',
                                rettype = 'Abstract',
                                id = pubmed_id,
                                api_key = 'your api key')

         results = handle.read()
         rec_file = io.StringIO(results)
         medline_rec = Medline.read(rec_file)

         if 'AB' in medline_rec.keys():
             ab = medline_rec['AB']
```
AB is for abstract. You need your own api_key from pubmed and also read usage restrictions.

**Comment by etetteh** [comment]
Thanks so much for sharing. I download a file from pubmed that contains
PMID(Pubmed ID), and found a way to download them in chunks using rentrez.
I wish I could download the number of Abstracts at one time, but it's all
well.

I really appreciate the response from you
