### ISSUE TITLE
Is there any plan to upload pretrained weight in a different format?

### ISSUE THREAD

**Issue by izuna385** [naver/biobert-pretrained#2]
Thanks for uploading pretrained weight.
`.ckpt` seems to be model from `tf`.
Because I am torch user, so I tried to find how to convert `tf` weights to `torch` weight(something like weight for `nn.Embedding`), but I couldn't find out.

Is there any plan to upload weight in the form of, say, GloVe txt format?
Like, one row is consisted from word and weight.
![image](https://user-images.githubusercontent.com/35322641/52134612-487b6e80-2687-11e9-9867-580be5688c5e.png)

If this could be done, I would do fine-tuning during training my model, for downstream tasks.
Thanks.

**Comment by jhyuklee** [comment]
For now, we don't have any plans to use different formats for pre-trained weights. But if you are a torch user (pytorch I guess), this closed issue might help: https://github.com/dmis-lab/biobert/issues/2. Thanks.

**Comment by izuna385** [comment]
Thanks, I'll try that.

**Comment by MeRajat** [comment]
I have converted this to pytorch for NER task.  https://github.com/MeRajat/SolvingAlmostAnythingWithBert .
