### ISSUE TITLE
License

### ISSUE THREAD

**Issue by yzhang123** [naver/biobert-pretrained#20]
Hi,

is it possible to add a License like Apache2.0 to the repo? So we can use these checkpoints for commercial purposes?
Thanks!

**Comment by jhyuklee** [comment]
Hi, the pre-trained weights are already licensed under Apache 2.0 in dmis-lab repository (https://github.com/dmis-lab/biobert/blob/master/LICENSE). You can use the checkpoints for commercial purposes and we have download links in the dmis-lab repository, too. Thanks.
