### ISSUE TITLE
Failed to find any matching files for biobert-pretrained/biobert_v1.1_pubmed/biobert_model.ckpt

### ISSUE THREAD

**Issue by votamvan** [naver/biobert-pretrained#8]
Hi biobert,
I got the error of not finding of file biobert_v1.1_pubmed/biobert_model.ckpt when I run the below command as written in README.md.
``
python run_ner.py \
    --do_train=true \
    --do_eval=true \
    --vocab_file=$BIOBERT_DIR/vocab.txt \
    --bert_config_file=$BIOBERT_DIR/bert_config.json \
    --init_checkpoint=$BIOBERT_DIR/biobert_model.ckpt \
    --num_train_epochs=10.0 \
    --data_dir=$NER_DIR/ \
    --output_dir=/tmp/bioner/
``
Would you please provide me the file biobert_model.ckpt or tell me how to fix the issue, thanks.

**Comment by jhyuklee** [comment]
Hi @votamvan,
The path might be wrong if you didn't set env variable $BIOBERT_DIR. Please check your path is properly set ($BIOBERT_DIR), and make sure that your files are there. Thank you.

**Comment by votamvan** [comment]
Hi @jhyuklee,

Thank you very much for your quick reply. I understand the variable $BIOBERT_DIR and already set it in my bash shell. The problem is about the missing file <biobert_model.ckpt>. After unpacking file biobert_v1.1_pubmed.tar.gz. I cannot find it anywhere. I enclose here content of unpacked folder for your review. I guess <biobert_model.ckpt> is forgot to attach in the package <biobert_v1.1_pubmed.tar.gz> or do I have to run some script to create the file <biobert_model.ckpt>. Please help me, thanks.

> 
biobert_v1.1_pubmed xxxxx$ pwd
/Users/xxxxx/biobert-pretrained/biobert_v1.1_pubmed
biobert_v1.1_pubmed xxxxx$ ls -l
total 871944
-rw-r--r--@ 1 xxxxx  staff     947465 Feb 26 15:25 model.ckpt-1000000.meta
-rw-r--r--@ 1 xxxxx  staff       8224 Feb 26 15:25 model.ckpt-1000000.index
-rw-r--r--@ 1 xxxxx  staff  433241088 Feb 26 15:25 model.ckpt-1000000.data-00000-of-00001
-rw-r--r--@ 1 xxxxx  staff        313 May 16 15:47 bert_config.json
-rw-r--r--@ 1 xxxxx  staff     213450 May 16 15:47 vocab.txt
>

**Comment by jhyuklee** [comment]
For that version, please try `init_checkpoint=$BIOBERT_DIR/model.ckpt`. Sorry for the inconsistency. We will update the readme.

**Comment by vnnp** [comment]
Hi @votamvan,
In this case, it worked for me only with `init_checkpoint=$BIOBERT_DIR/model.ckpt-1000000.index`

**Comment by v-loves-avocados** [comment]
I had the same problem. There was not a model.ckpt fille or biobert_model.ckpt. Instead, there are these three ckpt files: 

model.ckpt-1000000.data-00000-of-00001
model.ckpt-1000000.index
model.ckpt-1000000.meta

Thank you for your input.

**Comment by wonjininfo** [comment]
Hi @v-loves-avocados , 
You need to change parameter `--init_checkpoint=` according to the file name. 
Please ignore extensions(?) such as `.meta` or `.data~~` and use `--init_checkpoint=$BIOBERT_DIR/model.ckpt-1000000` instead.
Thanks!

**Comment by v-loves-avocados** [comment]
@wonjininfo  Thank you! It works! Successfully replicated the Relation Extraction results.
