### ISSUE TITLE
Can't download the pre-trained weight from "release" section

### ISSUE THREAD

**Issue by Enno-H** [naver/biobert-pretrained#9]
Hi Jinhyuk,

I have tried several times to download the files but failed.

Could you help me check whether the URL is still valid? 

Maybe uploading these files to S3 is a good choice.

Thanks

**Comment by jhyuklee** [comment]
Hi @click-me,

Please see the updated readme that contains Google Drive links for each pre-trained weights.
Thank you.

**Comment by Enno-H** [comment]
Hi @jhyuklee ,

Thanks for your work!
